// Chapter 1

// Question 1
// alert("Welcome to my First Website");

// Question 2
// alert("Error! Please enter a vali password");

// Question 3
// alert("Welcome to JS Land...\nHappy Coding!")

// Question 4
// alert("Welcome to JS Land...")
// alert("Happy Coding!\nPrevent this page from creating additional dialogs")

// Question 5
// Write in console
// alert("Hello... I can run JS through my web brower's console")
// and enter

//Question 6
// function myFunction() {
//     alert("Your are a very beautiful human being");
// }



// Chapter 2

// Question 1
// var userName;

// Question 2
// var myName;
// myName = "Muhammad Hammad Azhar";
// console.log(myName);

// Question 3
// var message;
// message = "Hello World";
// alert(message);

// Question 4
// var a;
// var b;
// var c;
// a = prompt("Your Name", "Name here");
// b = prompt("Your Age", "Age here");
// c = prompt("Degree", "Full degree here");
// alert(a);
// alert(b);
// alert(c);

// Question 5
// alert("PIZZA \n PIZZ \n PIZ \n PI \n P");

// Question 6
// var a = prompt("Your E-mail", "Email here")
// alert("My email address is " + a);

// Question 7
// var book = "A smarter way to learn JavaScript";
// alert("I am trying to learn from the Book " + book);

// Question 8
// document.write("Yah! I can write HTML content through JavaScript");

// Question 9
// var a = "▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬";
// alert(a);



// Chapter 3

// Question 1
// var age = 15;
// alert(`I am ${age} years old`);

// Question 2
// var num = Math.random() * 20;
// var num1 = Math.floor(num);
// alert(`You have visited this site ${num1} times`);

// Question 3
// var birthYear = 1997;
// document.write(`My birth year is ${birthYear} <br> Data type of my declared variable is number`)

// Question 4
// var name;
// var title;
// var quantity;
// name = prompt("Your Name", "Name here");
// title = prompt("Product title", "Title here");
// quantity = prompt("Product Quantity", "Quantity");
// document.write(`${name} ordered ${quantity} ${title}(s) on XYZ Clothing store `);